import {CollectedData} from '../models/CollectedData';

export const COLLECTED_DATA: CollectedData[] = [
    { date: "", listName: 'Competitive Intelligence', noOfEntities: 0, actions: false },
    { date: "", listName: 'My Vendors', noOfEntities: 0, actions: false },
    { date: "", listName: 'My Customers', noOfEntities: 0, actions: false },
    { date: "Jul 23", listName: 'Test_30_results', noOfEntities: 28, actions: true },
    { date: "Jun 28", listName: 'To_index', noOfEntities: 100, actions: true },
    { date: "Apr 10", listName: 'KPMG Requested Companies - Listed Set_Prasada Kumar', noOfEntities: 34, actions: true },
    { date: "Mar 12", listName: 'Error Case- LTB To EBITDA Blank_Prasada Kumar', noOfEntities: 24, actions: true },
    { date: "Dec 14", listName: 'Two Companies', noOfEntities: 2, actions: true },
    { date: "Nov 01", listName: 'Custom', noOfEntities: 30, actions: true },
    { date: "Oct 29", listName: 'Mumbai', noOfEntities: 3, actions: true },
    { date: "Feb 20", listName: 'Delhi', noOfEntities: 10, actions: true },
    { date: "Aug 07", listName: 'Kochi', noOfEntities: 8, actions: true },
    { date: "Oct 02", listName: 'Three Companies', noOfEntities: 3, actions: true },
    { date: "Jan 17", listName: 'Custom_2', noOfEntities: 12, actions: true }
  ];

  export const DESCRIPTIONS: String[] = [
    "Bundl Technologies Private Limited (Swiggy)",
    "Hector Bevarages Private Limited",
    "Puma Sports India Private Limited",
    "Dewan Housing Finance Corporation Ltd.",
    "Infosys Limited",
    "Think & Learn Private Limited",
    "Delhivery Private Limited",
    "Wow Momo Foods Private Limited",
    "Rebel Foods Private Limited (Faasos)",
    "Lendingkart Technologies Private Limited",
    "ID Fresh Food (India) Private Limited",
    "Bharathiasha Technologies Private Limited (PrivateCircle)",
    "Gala Precision Engineering Private Limited",
    "Balaji Wafers Private Limited",
    "Sangeetha Mobiles Private Limited",
    "Vodafone Idea Limited",
    "Vakrangee Ltd.",
    "Bundl Technologies Private Limited (Swiggy)",
    "Hector Bevarages Private Limited",
    "Puma Sports India Private Limited",
    "Dewan Housing Finance Corporation Ltd.",
    "Infosys Limited",
    "Think & Learn Private Limited",
    "Delhivery Private Limited",
    "Wow Momo Foods Private Limited",
    "Rebel Foods Private Limited (Faasos)",
    "Lendingkart Technologies Private Limited",
    "ID Fresh Food (India) Private Limited",
    "Bharathiasha Technologies Private Limited (PrivateCircle)",
    "Gala Precision Engineering Private Limited",
    "Balaji Wafers Private Limited",
    "Sangeetha Mobiles Private Limited",
    "Vodafone Idea Limited",
    "Vakrangee Ltd.",
    "Bundl Technologies Private Limited (Swiggy)",
    "Hector Bevarages Private Limited",
    "Puma Sports India Private Limited",
    "Dewan Housing Finance Corporation Ltd.",
    "Infosys Limited",
    "Think & Learn Private Limited",
    "Delhivery Private Limited",
    "Wow Momo Foods Private Limited",
    "Rebel Foods Private Limited (Faasos)",
    "Lendingkart Technologies Private Limited",
    "ID Fresh Food (India) Private Limited",
    "Bharathiasha Technologies Private Limited (PrivateCircle)",
    "Gala Precision Engineering Private Limited",
    "Balaji Wafers Private Limited",
    "Sangeetha Mobiles Private Limited",
    "Vodafone Idea Limited",
    "Vakrangee Ltd.",
    "Bundl Technologies Private Limited (Swiggy)",
    "Hector Bevarages Private Limited",
    "Puma Sports India Private Limited",
    "Dewan Housing Finance Corporation Ltd.",
    "Infosys Limited",
    "Think & Learn Private Limited",
    "Delhivery Private Limited",
    "Wow Momo Foods Private Limited",
    "Rebel Foods Private Limited (Faasos)",
    "Lendingkart Technologies Private Limited",
    "ID Fresh Food (India) Private Limited",
    "Bharathiasha Technologies Private Limited (PrivateCircle)",
    "Gala Precision Engineering Private Limited",
    "Balaji Wafers Private Limited",
    "Sangeetha Mobiles Private Limited",
    "Vodafone Idea Limited",
    "Vakrangee Ltd.",
    "Bundl Technologies Private Limited (Swiggy)",
    "Hector Bevarages Private Limited",
    "Puma Sports India Private Limited",
    "Dewan Housing Finance Corporation Ltd.",
    "Infosys Limited",
    "Think & Learn Private Limited",
    "Delhivery Private Limited",
    "Wow Momo Foods Private Limited",
    "Rebel Foods Private Limited (Faasos)",
    "Lendingkart Technologies Private Limited",
    "ID Fresh Food (India) Private Limited",
    "Bharathiasha Technologies Private Limited (PrivateCircle)",
    "Gala Precision Engineering Private Limited",
    "Balaji Wafers Private Limited",
    "Sangeetha Mobiles Private Limited",
    "Vodafone Idea Limited",
    "Vakrangee Ltd."
  ]

